const START=new Date(TRIP.start+"T09:00:00+01:00"),CAP=TRIP.cap;let day=1;
let E=JSON.parse(localStorage.getItem("sr56.expenses")||"[]"),N=JSON.parse(localStorage.getItem("sr56.notes")||"{}"),B=JSON.parse(localStorage.getItem("sr56.bookings")||"{}"),D=JSON.parse(localStorage.getItem("sr56.documents")||"[]");
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>"£"+Number(n||0).toLocaleString("en-GB",{maximumFractionDigits:0});
function nav(id,b){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");$$("nav button").forEach(x=>x.classList.remove("active"));if(b)b.classList.add("active");if(id==="bookings")bookings();if(id==="budget")budget();if(id==="documents")docs();scrollTo(0,0)}
function toast(t){let x=$("#toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",2000)}
function maps(q){open("https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(q),"_blank")}
function home(){let diff=START-new Date();day=diff>0?1:Math.min(56,Math.max(1,Math.floor(-diff/86400000)+1));let d=T[day-1];$("#route").textContent=d.route;$("#activity").textContent=d.morning+" · "+d.afternoon;$("#country").textContent=d.country;$("#hday").textContent="Day "+day;$("#count").textContent=diff>0?Math.floor(diff/86400000)+" days "+Math.floor((diff%86400000)/3600000)+" hours":"Day "+day+" of 56";$("#prog").style.width=(day/56*100)+"%";let planned=T.reduce((s,x)=>s+x.planned,0);$("#budgetLeft").textContent=money(CAP-planned)}
function journey(){let h="",c="";T.forEach(d=>{if(c!==d.country){c=d.country;h+=`<h3 class="section">${c}</h3>`}h+=`<button class="day" onclick="openDay(${d.day})"><span class="num">${d.day}</span><span class="copy"><span class="country">${d.date}</span><b>${d.route}</b><em>${d.morning}</em></span><b>›</b></button>`});$("#journey").innerHTML=h}
function openDay(n){day=n;let d=T[n-1],st=B[d.id]||d.status;$("#detail").innerHTML=`<button class="back" onclick="nav('journeyScreen')">‹ Journey</button><div class="country">${d.country} · ${d.date}</div><h1>Day ${n}</h1><h2>${d.route}</h2><div class="card timeline"><label>TIMELINE</label><div><b>Morning</b><p>${d.morning}</p></div><div><b>Afternoon</b><p>${d.afternoon}</p></div><div><b>Evening</b><p>${d.evening}</p></div></div><div class="card"><label>STAY</label><h3>${d.hotel}</h3><button class="soft" onclick='maps(${JSON.stringify(d.hotel+" "+d.route)})'>Open hotel in Maps ↗</button></div><div class="card"><label>TRANSPORT / TICKET</label><h3>${d.transport}</h3><p>${d.journeyTime}</p><div class="status">Status: <b>${st}</b></div><button class="soft" onclick="nav('bookings')">Manage booking status →</button></div><div class="card"><label>PLANNED COST</label><h3>${money(d.planned)} pp</h3></div><div class="card"><label>MAP</label><button class="soft" onclick='maps(${JSON.stringify(d.route)})'>Open this day in Maps ↗</button></div><div class="card"><label>JOURNAL NOTE</label><textarea id="note">${N[n]||""}</textarea><button class="primary" onclick="saveNote(${n})">Save offline</button></div>`;nav("detail")}
function saveNote(n){N[n]=$("#note").value;localStorage.setItem("sr56.notes",JSON.stringify(N));toast("Note saved offline")}
function bookings(){let booked=0;$("#bookingList").innerHTML=T.map(d=>{let s=B[d.id]||"Estimated";if(s==="Booked"||s==="Paid")booked++;return `<div class="card booking"><span class="country">Day ${d.day} · ${d.country}</span><h3>${d.route}</h3><p>${d.transport}</p><select onchange="setBooking('${d.id}',this.value)"><option ${s==="Estimated"?"selected":""}>Estimated</option><option ${s==="Quoted"?"selected":""}>Quoted</option><option ${s==="Booked"?"selected":""}>Booked</option><option ${s==="Paid"?"selected":""}>Paid</option></select></div>`}).join("");$("#bookedCount").textContent=booked+" / 56"}
function setBooking(id,v){B[id]=v;localStorage.setItem("sr56.bookings",JSON.stringify(B));bookings();toast("Booking status updated")}
function budget(){let planned=T.reduce((s,x)=>s+x.planned,0),actual=E.reduce((s,x)=>s+x.a,0),by={};T.forEach(x=>by[x.country]=(by[x.country]||0)+x.planned);$("#budgetSummary").textContent=money(planned)+" planned · "+money(CAP-planned)+" reserve · "+money(actual)+" actual spend logged";$("#countryBudget").innerHTML=Object.entries(by).map(([c,v])=>`<div class="row"><span>${c}</span><b>${money(v)}</b></div>`).join("")}
function addExpense(){let d=$("#ed").value.trim(),a=Number($("#ea").value),c=$("#ec").value;if(!d||a<=0)return toast("Enter description and amount");E.push({id:Date.now(),d,a,c,day});localStorage.setItem("sr56.expenses",JSON.stringify(E));$("#ed").value="";$("#ea").value="";expenses();home();toast("Expense saved offline")}
function expenses(){let total=E.reduce((s,e)=>s+e.a,0);$("#spent").textContent="£"+total.toFixed(2);$("#expenseList").innerHTML=E.length?E.map(e=>`<div class="row"><span>${e.d}<br><small>Day ${e.day} · ${e.c}</small></span><b>£${e.a.toFixed(2)}</b></div>`).join(""):"<p>No expenses yet.</p>"}
function addDoc(){let n=$("#docName").value.trim(),r=$("#docRef").value.trim();if(!n)return toast("Enter a document name");D.push({id:Date.now(),name:n,ref:r});localStorage.setItem("sr56.documents",JSON.stringify(D));$("#docName").value="";$("#docRef").value="";docs();toast("Document reference saved offline")}
function docs(){$("#docList").innerHTML=D.length?D.map(x=>`<div class="card"><h3>${x.name}</h3><p>${x.ref||"No reference added"}</p></div>`).join(""):"<div class='card'><p>No document references yet.</p></div>"}
function notify(){if(!("Notification"in window))return toast("Notifications unavailable");Notification.requestPermission().then(p=>toast(p==="granted"?"Alerts enabled":"Permission not granted"))}
function install(){toast("iPhone: Share → Add to Home Screen. Android: browser menu → Install app.")}
journey();expenses();docs();home();setInterval(home,60000);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");