const TRIP={name:"SilkRoute 56",start:"2028-05-15",end:"2028-07-09",cap:20000};
const T=[
["Uzbekistan","London → Tashkent","Hyatt Regency Tashkent","Fly London → Tashkent","Arrival, private transfer & settle in","Light dinner / early night","International flight + private transfer","~9–12h incl. connection",830],
["Uzbekistan","Tashkent","Hyatt Regency Tashkent","Khast Imam complex","Chorsu Bazaar, Metro & city highlights","Uzbek dinner","Private guide/driver","Full day",255],
["Uzbekistan","Tashkent → Samarkand","Mövenpick Samarkand","Afrosiyob to Samarkand","Registan orientation & old city","Registan illuminated","Business-class train + taxi","~2h15 rail",230],
["Uzbekistan","Samarkand","Mövenpick Samarkand","Gur-e-Amir & Registan","Bibi-Khanym, Siab Bazaar, Shah-i-Zinda","Free evening","Private guide/driver","Full day",225],
["Uzbekistan","Samarkand","Mövenpick Samarkand","Ulugh Beg Observatory & Afrasiab","Konigil paper village","Relaxed dinner","Private guide/driver","Half/full day",205],
["Uzbekistan","Samarkand → Bukhara","Mercure Bukhara Old Town","Afrosiyob to Bukhara","Lyabi-Hauz & trading domes","Old-town dinner","Business-class train + taxi","~1h45 rail",210],
["Uzbekistan","Bukhara","Mercure Bukhara Old Town","Poi Kalyan & Ark","Bolo Hauz, Chor Minor & Jewish quarter","Free evening","Walking/private guide","Full day",205],
["Uzbekistan","Bukhara → Khiva","Farovon Khiva","Private drive across Kyzylkum","Arrival & Itchan Kala orientation","Sunset in old city","Private car/driver","~6–7h",235],
["Uzbekistan","Khiva","Farovon Khiva","Kunya Ark & Kalta Minor","Juma Mosque, Tash Hauli & Islam Khoja","Old-city dinner","Walking/private guide","Full day",195],
["Kazakhstan","Khiva → Almaty","Novotel Almaty City Center","Transfer to Urgench airport","Fly to Almaty (routing TBD)","Settle in","Private transfer + regional flight","~5–8h incl. connection",390],
["Kazakhstan","Almaty","Novotel Almaty City Center","Green Bazaar & cathedral","Medeu & Shymbulak","City dinner","Private guide/driver","Full day",240],
["Kyrgyzstan","Almaty → Bishkek","Novotel Bishkek City Center","Drive Almaty → Bishkek","Border crossing & arrival","Ala-Too Square stroll","Private car/driver","~4–5h",220],
["Kyrgyzstan","Bishkek → Issyk-Kul","Karven Four Seasons","Bishkek → Burana Tower","Continue to Issyk-Kul","Lakeside evening","Private 4WD/driver","~5–6h with stops",240],
["Kyrgyzstan","Issyk-Kul → Karakol","Green Yard / Karagat","Cholpon-Ata / lakeshore","Scenic drive to Karakol","Local dinner","Private 4WD/driver","~4–5h",195],
["Kyrgyzstan","Karakol","Green Yard / Karagat","Dungan Mosque & cathedral","Jeti-Ögüz excursion","Relax","Private 4WD/guide","Full day",195],
["Kyrgyzstan","Karakol → Naryn","Grand Khan Tengri","Southern Issyk-Kul route","Scenic drive to Naryn","Early night","Private 4WD/driver","~7–8h",200],
["Kyrgyzstan","Naryn → Tash Rabat","Premium yurt camp","Naryn → Tash Rabat","Caravanserai & valley walk","Yurt dinner / stars","Private 4WD","~2–3h",175],
["China","Tash Rabat → Torugart → Kashgar","Radisson Blu Kashgar","Tash Rabat → Torugart","Border formalities / vehicle handover","Arrive Kashgar; rest","Kyrgyz + Chinese private vehicles","Full day / variable",470],
["China","Kashgar","Radisson Blu Kashgar","Late breakfast & old city","Id Kah area, crafts & tea houses","Food streets","Private local guide","Easy day",190],
["China","Kashgar","Radisson Blu Kashgar","Abakh Khoja Tomb","Old-city lanes & workshops","Free evening","Private guide/driver","Full day",205],
["China","Kashgar","Radisson Blu Kashgar","Sunday livestock market","Bazaar & local neighbourhoods","Relax","Private guide/driver","Full day",210],
["China","Kashgar → Tashkurgan","Upscale local hotel","Kashgar → White Sand Lake","Karakul Lake & Muztagh Ata","Arrive Tashkurgan","Private SUV + guide","~6–8h with stops",280],
["China","Tashkurgan → Kashgar","Radisson Blu Kashgar","Stone Fort & grasslands","Return Karakoram Highway","Kashgar dinner","Private SUV + guide","~6–8h",285],
["China","Kashgar → Turpan","Soft-sleeper berth","Free morning in Kashgar","Board train east","Overnight sleeper","Soft-sleeper train","~13–16h",120],
["China","Turpan","Mercure Turpan Downtown","Arrive / check in","Easy city sightseeing","Rest","Taxi/private transfer","Arrival day",145],
["China","Turpan","Mercure Turpan Downtown","Jiaohe & Karez","Emin Minaret, Flaming Mountains, Bezeklik","Dinner","Private driver/guide","Full day",210],
["China","Turpan → Dunhuang","Dunhuang Silk Road Hotel","Rail east toward Dunhuang","Transfer / arrival","Free evening","Rail + private transfer","~7–10h TBD",195],
["China","Dunhuang","Dunhuang Silk Road Hotel","Mogao Caves","Mingsha dunes & Crescent Moon Spring","Desert sunset","Private guide/driver","Full day",225],
["China","Dunhuang","Dunhuang Silk Road Hotel","Yangguan / western sites","Desert landscapes","Relax","Private guide/driver","Full day",215],
["China","Dunhuang → Jiayuguan","Jiayuguan 4-star","Train to Jiayuguan","Fortress orientation","Local dinner","High-speed rail + taxi","~2.5–3h",155],
["China","Jiayuguan","Jiayuguan 4-star","Jiayuguan Fortress","Overhanging Wall & First Beacon","Free evening","Private driver/guide","Full day",200],
["China","Jiayuguan → Zhangye","Huachen International","High-speed rail to Zhangye","City / Dafo Temple","Danxia sunset","Rail + private driver","~1.5–2h rail",180],
["China","Zhangye → Beijing","Park Plaza Wangfujing","Fly Zhangye → Beijing","Transfer / settle in","Wangfujing evening","Domestic flight + transfer","~4–6h total",350],
["China","Beijing","Park Plaza Wangfujing","Tiananmen area & Forbidden City","Jingshan & hutongs","Peking duck","Private guide/driver","Full day",275],
["China","Beijing","Park Plaza Wangfujing","Mutianyu Great Wall","Summer Palace if energy permits","Free evening","Private car/guide","Full day",290],
["Mongolia","Beijing → Ulaanbaatar","Best Western Premier Tuushin","Beijing → Ulaanbaatar","Travel / border or flight","Arrival","International train/flight TBD","~2h flight or overnight rail",325],
["Mongolia","Ulaanbaatar","Best Western Premier Tuushin","Gandan Monastery","National Museum & Sukhbaatar Square","Prepare for Gobi","Private guide/driver","Full day",205],
["Mongolia","Ulaanbaatar → Gobi","Premium ger lodge","Fly to Dalanzadgad","Yolyn Am / desert entry","Ger camp dinner","Domestic flight + private 4WD","~1.5h flight + touring",585],
["Mongolia","Gobi","Premium ger lodge","Gobi exploration","Flaming Cliffs / Bayanzag","Camp evening","Private 4WD/guide","Full day",495],
["Mongolia","Gobi","Premium ger lodge","Dunes / camel country","Nomadic family experience","Camp evening","Private 4WD/guide","Full day",495],
["Mongolia","Gobi → Ulaanbaatar","Best Western Premier Tuushin","Return toward Dalanzadgad","Fly to Ulaanbaatar","Comfortable hotel night","Private 4WD + domestic flight","Travel day",315],
["South Korea","Ulaanbaatar → Seoul","L7 Myeongdong / Novotel","Fly Ulaanbaatar → Seoul","Transfer & settle in","Myeongdong","International flight + rail/taxi","~3–4h flight",340],
["South Korea","Seoul","L7 Myeongdong / Novotel","Gyeongbokgung","Bukchon & Insadong","Cheonggyecheon / dinner","Private/small-group guide","Full day",225],
["South Korea","Seoul","L7 Myeongdong / Novotel","DMZ excursion if operating","Return / contemporary Seoul","Free evening","Coach/private tour","Half/full day",240],
["South Korea","Seoul → Gyeongju","Hilton Gyeongju","KTX Seoul → Singyeongju","Royal tombs & historic centre","Donggung/Wolji","KTX + taxi","~2h rail",250],
["South Korea","Gyeongju","Hilton Gyeongju","Bulguksa & Seokguram","National Museum / old city","Relax","Private guide/driver","Full day",245],
["South Korea","Gyeongju → Busan","L7 Haeundae","Train to Busan","Gamcheon & Jagalchi","Haeundae","Train + local transport","~1h",205],
["South Korea","Busan → Fukuoka","New Camellia deluxe twin","Haedong Yonggungsa","Free afternoon / ferry check-in","Sail Busan → Fukuoka","Local transport + overnight ferry","Overnight",250],
["Japan","Fukuoka → Hiroshima","Hotel Granvia Hiroshima","Arrive Hakata / breakfast","Shinkansen to Hiroshima","Peace Park & Museum","Shinkansen + local","~1h rail",245],
["Japan","Hiroshima / Miyajima","Hotel Granvia Hiroshima","Miyajima / Itsukushima","Daisho-in & Mt Misen","Return Hiroshima","Train + ferry","Full day",220],
["Japan","Hiroshima → Kyoto","Cross Hotel / Royal Park","Shinkansen Hiroshima → Kyoto","Gion & Higashiyama orientation","Pontocho","Green Car + local","~2h",295],
["Japan","Kyoto","Cross Hotel / Royal Park","Fushimi Inari early","Kiyomizu-dera & Higashiyama","Gion evening","Private guide/local transport","Full day",275],
["Japan","Kyoto → Tokyo","Hotel Metropolitan Marunouchi","Kinkaku-ji or Arashiyama","Shinkansen Kyoto → Tokyo","Ginza / dinner","Shinkansen + local","~2h15 rail",335],
["Japan","Tokyo","Hotel Metropolitan Marunouchi","Meiji Shrine & Harajuku","Shibuya & Ginza","Skyline viewpoint","Local transport","Full day",280],
["China","Tokyo → Shanghai","Bund-area 4/5-star","Fly Tokyo → Shanghai","Bund / French Concession","Final-night dinner","Flight + private transfer","~3h flight",390],
["China","Shanghai → London","—","Yu Garden / final stroll if flight allows","Private transfer to airport","Fly Shanghai → London","International flight + transfer","~12–15h direct/total",710]
].map((x,i)=>({id:"SR56-D"+String(i+1).padStart(2,"0"),day:i+1,date:new Date(2028,4,15+i).toISOString().slice(0,10),country:x[0],route:x[1],hotel:x[2],morning:x[3],afternoon:x[4],evening:x[5],transport:x[6],journeyTime:x[7],planned:x[8],status:"Estimated"}));